### ISSUE TITLE
Knowledge graph broken?

### ISSUE THREAD

**Issue by mattlindsey** [nickthecook/archyve#138]
I think we may have broken something.   If I do `ops rails db:drop` then `ops rails db:setup` to try to reset everything, I get errors if knowledge graph is enabled for a collection
Also I can't set the field below. Maybe it's just me, so can someone else try it?

![image](https://github.com/user-attachments/assets/27b8af79-5506-44ee-a298-5c2c7e0b3a8a)

**Comment by mattlindsey** [comment]
I forgot that I need to do `ops rails neo4j:migrate` also.
So I deleted the container and image in docker and did all the steps in the README like I did before (https://github.com/nickthecook/archyve?tab=readme-ov-file#running-an-archyve-container) , but still not working.

This problem may still be specific to just me, but it would be good to figure out.

**Comment by nickthecook** [comment]
Hey Matt, with respect to the knowledge graph model, do you have a model available that meets the requirements described in the text on that page?

**Comment by nickthecook** [comment]
That error in your logs does look like it's trying to do entity extraction without an entity extraction model. Looks like that app needs to be smarter about existing collections when there is no extraction model available.

If you create a model in Ollama with a large enough context window and then set that as your extraction model, that should fix it for you. I plan to have Archyve do that for the user eventually but for now it's manual.
