### ISSUE TITLE
Use LLM to generate titles

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/archyve#2]

**Comment by nickthecook** [comment]
Partially done, but poorly.

Do it [this way](https://github.com/huggingface/chat-ui/blob/main/src/lib/server/summarize.ts).

Depends on #1, because we can't do it that way until we can encode multiple, separate messages into one prompt, using start and stop tokens.

**Comment by oxaronick** [comment]
Fixed a while ago, definitely done by 1.7.0.
