### ISSUE TITLE
Support multiple simultaneous users with TurboStreams

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/archyve#22]
The app works fine for one user, but many TurboStream broadcasts are going to affect users that shouldn't be affected by them.

For example, the `search_results` dom_id means that if two users on the search page and one searches, the search results will show up in both users' windows.

In general:

- [x] make the channels specific to an area of the app that all users can access
  - e.g. if we want to limit user access per collection, make a separate channel per collection, so we don't broadcast to users that can't see the collection
 - [x] make the dom_ids different for every page
  - e.g. `search_results` vs. `global_search_results`
- [x] make the dom_ids specific to the model, if updates are broadcast by the model
- [x] make the dom_ids specific to each page load (i.e. randomized) if updates are being broadcast by a service or controller

**Comment by nickthecook** [comment]
Search result dom_ids are per-user, but multiple windows for the same user can still cause updates in the other window.

**Comment by oxaronick** [comment]
Fixed fully in 1.8.1.
