### ISSUE TITLE
Allow changing ModelServers without changing ModelConfigs

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/archyve#33]
In the case where the user:

1. creates a collection and adds documents, embedding them with whatever embedding model is the configured one at the time
2. changes ModelServers (and thus, ModelConfigs, since one ModelConfig cannot belong to multiple ModelServers)
3. tries to search his or her documents

The ModelConfig with which the Collection was embedded will be used to embed the query. This makes sense, and the embedding model used for embedding the query must be the same as the one used to embed the documents.

However, which server is running the ModelConfig is not important. If I switch ModelServers, say because I'm not at home and my PC with its GPU is not available, but I want to continue to query my documents, I have to use the admin UI to change the embedding model for all my collections (or edit the ModelServer to have a different hostname).

It would be nice to support this use case. Maybe ModelConfigs:ModelServers is many:many, or maybe there is "switch model server" functionality built in to allow the user to reconfigure ModelConfigs as a batch.

**Comment by oxaronick** [comment]
Fixed in 1.7.0.
