### ISSUE TITLE
compose.yaml incorrect port mapping

### ISSUE THREAD

**Issue by advaitian** [nickthecook/archyve#66]
**_compose.yaml requires to correct port mapping form 3300:3000 to 3300:3300_**

...
  archyve:
    image: archyve:local
    build: .
    env_file: ./local.env
    restart: unless-stopped
    volumes:
      - archyve_files:/rails/storage
      - ./config/local:/rails/config/local
    # this needs to be edited to give podman access to host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      **- 3300:3300**
    depends_on:
      - redis
      - postgres
   ...

**Comment by nickthecook** [comment]
Thanks for logging the issue, @advaitian .

Fixed in `main`.
