### ISSUE TITLE
Add SearchRequest model

### ISSUE THREAD

**Issue by nickthecook** [nickthecook/archyve#7]
Add SearchRequest to track the results of a search. This can be used to:

- allow the user to send a message in a conversation and get an event with a link to the SearchResult, to get info on what Archyve found for their prompt
- allow admins to see what happened when users report a poor response, whether directly or through a downvote feature later
- allow analytics of search result quality over time

SearchResult would:

- have many Chunks
- have a prompt
- optionally belong to a Conversation
  - when created as part of a Conversation, conversation is set
  - when created from the Search Collection page, no conversation is set
- belong to a User

**Comment by oxaronick** [comment]
This can also be used to send TurboStream broadcasts and remove all that stuff from Services.

**Comment by nickthecook** [comment]
This has been implemented with the `prompt` field in Message and the MessageAugmentation model.
