### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen - /rails/config/local/encryption_keys.json (Errno::EACCES)

### ISSUE THREAD

**Issue by virdb** [nickthecook/archyve#74]
I'm trying to run archyve on a docker box ubuntu based. Following the steps to install, the containers starts, but some of them (**archyve-archyve-worker-llm-1,** **archyve-archyve-worker-1**, **archyve-archyve-ollamaproxy-1** and **archyve-archyve-1**) are in a restarting loop.

I suspect the root cause is this error in **archyve-archyve-1** container, but I've no idea how to solve:

```
Waiting for 'postgres:5432' to be open...
/usr/local/bundle/ruby/3.2.0/gems/io-event-1.6.5/lib/io/event/support.rb:27: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
W, [2024-09-13T07:45:12.555868 #117]  WARN -- : No encryption keys found, generating new ones in /rails/config/local/encryption_keys.json...
bin/rails aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /rails/config/local/encryption_keys.json (Errno::EACCES)
/rails/config/initializers/active_record_encryption.rb:11:in `write'
/rails/config/initializers/active_record_encryption.rb:11:in `write'
/rails/config/initializers/active_record_encryption.rb:11:in `<main>'
/rails/config/environment.rb:5:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by nickthecook** [comment]
Thanks for opening the issue.

Do you have a `config/local` directory after trying to run the containers? If so, what are the file permissions?

Have you made any modifications to the compose file from the repo?

**Comment by virdb** [comment]
> Thanks for opening the issue.

Thank for your software!

> Do you have a `config/local` directory after trying to run the containers? If so, what are the filesystem permissions?

yes (config/local only contains an empty .keep file:
```
root@cuda01:~/repos/archyve# ls -alhd config/
drwxr-xr-x 7 root root 4.0K Sep 13 07:22 config/
root@cuda01:~/repos/archyve# ls -alhd config/local
drwxr-xr-x 2 root root 4.0K Sep 13 07:22 config/local
```

> Have you made any modifications to the compose file from the repo?

No, just configured the key in the local.env (ollama runs on the same node)

**Comment by nickthecook** [comment]
Hm... `config/local` is owned by `root` and no other user will be able to create a file in it.

Are you logged in as `root`, or do you run docker stuff as `root`? Any idea why that dir would be `root`?

If you're not logged in as `root`, try something like `sudo chown $USER config/local` or `sudo chmod 666 config/local`.

Basically, Archyve needs to be able to write a file to that directory, and if the user it's running as can't do that, Archyve can't start. You could create the file yourself, but it's probably easier to solve the permissions issue and have Archyve do it.

**Comment by virdb** [comment]
> Hm... `config/local` is owned by `root` and no other user will be able to create a file in it.
> 
> Are you logged in as `root`, or do you run docker stuff as `root`? Any idea why that dir would be `root`?
> 
> If you're not logged in as `root`, try something like `sudo chown $USER config/local` or `sudo chmod 666 config/local`.

Actually, I'm root and all my docker stuff is running as root

> Basically, Archyve needs to be able to write a file to that directory, and if the user it's running as can't do that, Archyve can't start. You could create the file yourself, but it's probably easier to solve the permissions issue and have Archyve do it.

I tried to chmod -R a+w the directory. a file is created with the 1000:1000 owner, however **archyve-archyve-worker-llm-1** and **archyve-archyve-ollamaproxy-1** still stay in a restarting loop. Here the logs:

archyve-archyve-worker-llm-1:

```
Waiting for 'postgres:5432' to be open...
/usr/local/bundle/ruby/3.2.0/gems/io-event-1.6.5/lib/io/event/support.rb:27: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
2024-09-13T13:11:16.479Z pid=9 tid=4gt INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://redis:6379"}
2024-09-13T13:11:16.490Z pid=9 tid=4gt INFO: Cron Jobs - deleted job with name: clean_api_calls
2024-09-13T13:11:16.490Z pid=9 tid=4gt INFO: Cron Jobs - deleted all jobs
2024-09-13T13:11:16.490Z pid=9 tid=4gt INFO: Loading Sidekiq Cron jobs hash: {"clean_api_calls"=>{"cron"=>"0 12 * * *", "class"=>"CleanApiCallsJob", "args"=>[], "description"=>"Remove ApiCalls older than 14 days from the database", "status"=>"enabled"}}
2024-09-13T13:11:16.495Z pid=9 tid=4gt INFO: Cron Jobs - added job with name: clean_api_calls
Seeding database with USERNAME 'admin@archyve.io', PASSWORD '********', and endpoint 'http://localhost:11434'...
DEFAULT_CLIENT_ID and DEFAULT_API_KEY not set; not creating or updating default client.
provisioning model server for `{"name"=>"ollama", "url"=>"http://host.docker.internal:11434", "provider"=>"ollama"}` ...
provisioning model configuration for `{"name"=>"llama3.1:8b", "model"=>"llama3.1:8b", "temperature"=>0.1}` ...
provisioning model configuration for `{"name"=>"nomic-embed-text", "model"=>"nomic-embed-text", "embedding"=>true}` ...
missing argument: -c
/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/cli.rb:343:in `parse_options'
/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/cli.rb:251:in `setup_options'
/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/lib/sidekiq/cli.rb:29:in `parse'
/usr/local/bundle/ruby/3.2.0/gems/sidekiq-7.2.2/bin/sidekiq:27:in `<top (required)>'
/usr/local/bundle/ruby/3.2.0/bin/sidekiq:25:in `load'
/usr/local/bundle/ruby/3.2.0/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
```

archyve-archyve-ollamaproxy-1:
```
Waiting for 'postgres:5432' to be open...
/usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/parser/arguments.rb:143:in `parse_numeric': Expected numeric value for '--port'; got "" (Thor::MalformattedArgumentError)
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/parser/options.rb:291:in `parse_peek'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/parser/options.rb:116:in `parse'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/base.rb:95:in `initialize'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:26:in `initialize'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/shell.rb:45:in `initialize'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command/environment_argument.rb:17:in `initialize'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/server/server_command.rb:126:in `initialize'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:523:in `new'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:523:in `dispatch'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:73:in `perform'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:71:in `block in invoke'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
	from /usr/local/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /rails/bin/rails:4:in `<main>'
```

**Comment by nickthecook** [comment]
The error from `archyve-archyve-ollamaproxy-1` is odd, because it appears to be missing `$OPP_PORT`, but that variable is defined right in the compose file, just above it.

You could try setting that variable in your `local.env` file as well, even though I haven't had to do that:

```
OPP_PORT=11337
OPP_BIND_ADDRESS=0.0.0.0
```

What is the output of `docker -v` on your machine?

**Comment by nickthecook** [comment]
Sounds like the initial access problem is solved, but you've now got an issue where some env vars are not being set by `docker compose`.

I can't reproduce this on Mac with Docker, but I can reproduce it with Podman. I'll keep looking into it and update you here when I have a fix.

**Comment by nickthecook** [comment]
I've pushed an update where the three variables that weren't being set are just hard-coded. LMK if that works.

I'll work on a way to make them configurable again, but it should work in the meantime.

**Comment by jalewis** [comment]
Just to confirm, I had the same issue with encryption_keys.json not being created, which prevents the containers from working properly.  I changed the permissions on config/local to 777 and on restart, encryption_keys.json is created with 1000:1000 UID:GID.  After that permission change, I seem to be up and running.  Maybe something is being created with hardcoded user and group?

**Comment by nickthecook** [comment]
Are you on Linux, @jalewis?

What is the output of `docker -v`?

**Comment by jalewis** [comment]
Yes, ubuntu 24.04.1

docker -v
Docker version 27.2.1, build 9e34c9b

**Comment by nickthecook** [comment]
> Yes, ubuntu 24.04.1
> 
> 
> 
> docker -v
> 
> Docker version 27.2.1, build 9e34c9b
> 
> 

Are you running docker as `root` as well?

**Comment by jalewis** [comment]
Not running docker as root.   But my username is not UID 1000.

**Comment by virdb** [comment]
> chmod -R a+w the directory. a file is created with the 1000:1000 owner, however **archyve-archyve-worker-llm-1** and **archyve-archyve-ollamaproxy-1** still stay in a restarting loop. Here the logs:



> That error about `missing argument: -c` looks like the `$LLM_JOBS_CONCURRENCY` env var isn't set, so this command from the compose file will have a trailing `-c`:

This seems to be actually right:

```
marco@expiess:~/repos/archyve$ docker compose up --build
WARN[0000] The "OPP_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "OPP_BIND_ADDRESS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LLM_JOBS_CONCURRENCY" variable is not set. Defaulting to a blank string. 
...
```

but...

> 
> ```yaml
>     command:
>       [
>         "/bin/bash",
>         "-c",
>         "bin/rails db:seed && bundle exec sidekiq -q llm -c $LLM_JOBS_CONCURRENCY",
>       ]
> ```
> 
> `dotenv_template` has this line in it:
> 
> ```
> LLM_JOBS_CONCURRENCY=5
> ```
> 
> Did that line make it into your `local.env` file?

... yes! 

```
marco@expiess:~/repos/archyve$ ll local.env 
-rw-rw-r-- 1 marco marco 810 set 13 11:01 local.env

```

and LLM_JOBS_CONCURRENCY is present:

```
marco@expiess:~/repos/archyve$ cat local.env 
DATABASE_URL=postgres://archyve:password@postgres:5432/archyve?sslmode=disable
REDIS_URL=redis://redis:6379
SECRET_KEY_BASE=c4e197d931f481c5659a8485680c6603fd62c47e7bb885fe615ec4429532dd841e6943dffdf2452f3dff7dbabfefb5fc36e3460ab399f6d0a451b65e10a85c46
CHROMADB_HOST=chromadb
CHROMADB_PORT=8000
NEO4J_URL="neo4j://neo4j:7687"
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=password
USERNAME=admin@archyve.io
PASSWORD=password
PROVISIONED_MODEL_SERVERS="[
  {
    \"name\": \"ollama\",
    \"url\": \"http://192.168.1.4:11434\",
    \"provider\": \"ollama\"
  }
]"
PROVISIONED_MODEL_CONFIGS="[
  {
    \"name\": \"llama3.1:8b\",
    \"model\": \"llama3.1:8b\",
    \"temperature\": 0.1
  },
  {
    \"name\": \"nomic-embed-text\",
    \"model\": \"nomic-embed-text\",
    \"embedding\": true
  }
]"
LLM_JOBS_CONCURRENCY=5
```

I thinks the problem is the filename '**local.env**'. This should be some apple-ish :)
Ususally in linux the file is named "**.env**". Renaming it seems to solve, but I think I should set also OPP_PORT and OPP_BIND_ADDRESS, because **archyve-archyve-ollamaproxy-1** is still restarting complaining about:

```
Waiting for 'postgres:5432' to be open...
/usr/local/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/parser/arguments.rb:143:in `parse_numeric': Expected numeric value for '--port'; got "" (Thor::MalformattedArgumentError)

```

**Comment by virdb** [comment]
> ```
> OPP_PORT=11337
> OPP_BIND_ADDRESS=0.0.0.0
> ```

fixing those variables in the .env file seems to fix.

**Comment by oxaronick** [comment]
Reopening because I had to revert the commit.

I'll work on something that just puts these two vars in the .env file.
